services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ltcats_test_db
    volumes:
      - "postgres-data:/var/lib/postgesql"
volumes:
  postgres-data:
